name: GAGS
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - open-clip-torch
  - cuda-toolkit=11.8
  - plyfile=0.8.1
  - python=3.8.19
  - pip=22.3.1
  - pytorch=2.1.0=py3.8_cuda11.8_cudnn8.7.0_0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - tqdm
  - tensorboard
  - matplotlib
  - typing
  - pathlib
  - pip:
    - jaxtyping
    - opencv-python
    - gsplat
    - open3d
    - mediapy
    - submodules/segment-anything
    - submodules/simple-knn